name: Docker Image CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
 
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch the full commit history to get a unique SHA for tagging
    - name: Build the Docker image
      id: build
      run: |
        docker build . --file Dockerfile --tag kweg/pole-libretranslate:${{ steps.build.outputs.sha }}
        echo ::set-output name=sha::$(echo ${{ steps.build.outputs.sha }})
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username kweg --password-stdin
    - name: Tag and Push the Docker Image
      run: |
        docker push kweg/pole-libretranslate:${{ steps.build.outputs.sha }}