
name: Docker CI

on:
  pull_request:
    branches:
      - "develop"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          docker build -t omnipoly-test --target build-stage .
          docker run --rm omnipoly-test npm run test
